# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        files: ^skepticoin/
        pass_filenames: false
        language: system
        entry: mypy
        args: [skepticoin, --strict, --implicit-reexport, --allow-subclassing-any, --allow-any-generics, --ignore-missing-imports]
-   repo: local
    hooks:
      - id: pytest-check
        verbose: true
        name: pytest-check
        entry: python -m py.test tests/ -x
        language: system
        pass_filenames: false
        always_run: true